name: CC CI
on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  sdk_version: 7.40.00.77

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      sdk_version: ${{ env.sdk_version }}
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ env.sdk_version }}
          cache-from: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          push: true
